name: "Get Current Step"
description: "Determines the current active step number from workflows"
outputs:
  step_number:
    description: "The current step number extracted from the active workflow"
    value: ${{ steps.get_step_number.outputs.step_number }}

runs:
  using: "composite"
  steps:
    - name: Get step number from workflow
      uses: actions/github-script@v7
      id: get_step_number
      with:
        script: |
          const workflows = await github.rest.actions.listRepoWorkflows({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          const stepWorkflow = workflows.data.workflows.find(
            w => w.name.startsWith('Step') && w.state === 'active'
          );
          if (!stepWorkflow) {
            core.setFailed('No active workflow starting with "Step" found.');
            return;
          }
          const match = stepWorkflow.path.match(/\/(\d+)-step\.yml$/);
          if (!match) {
            core.setFailed('Could not extract number from workflow path.');
            return;
          }
          core.setOutput('step_number', match[1]);
