name: Step 3

on:
  push:
    branches:
      - main
    paths:
      - _config.yml

permissions:
  contents: read
  actions: write
  issues: write

env:
  STEP_4_FILE: ".github/steps/4-step.md"

jobs:
  check_step_work:
    name: Check step work
    runs-on: ubuntu-latest
    steps:
      - name: Find Exercise Issue
        id: find-exercise-issue
        uses: skills/exercise-toolkit/actions/find-exercise-issue@find-exercise-issue-action

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/exercise-toolkit
          path: exercise-toolkit
          ref: v0.4.0

      - name: Check for theme minima in _config.yml
        id: check-theme-minima
        continue-on-error: true
        uses: skills/action-keyphrase-checker@v1
        with:
          text-file: _config.yml
          keyphrase: "theme: minima"

      - name: Build message - step results
        id: build-message-step-results
        uses: skills/action-text-variables@v2
        with:
          template-file: exercise-toolkit/markdown-templates/step-feedback/step-results-table.md
          template-vars: |
            step_number: 3
            passed: ${{ !contains(steps.*.outcome, 'failure') }}
            results_table:
              - description: "Looked for minima theme added to the configuration file"
                passed: ${{ steps.check-theme-minima.outcome == 'success' }}

      - name: Create comment - step results
        run: |
          gh issue comment "$ISSUE_URL" \
            --body "$COMMENT_BODY" \
            --edit-last
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_BODY: ${{ steps.build-message-step-results.outputs.updated-text }}
          ISSUE_URL: ${{ steps.find-exercise-issue.outputs.issue-url }}

      - name: Fail job if not all checks passed
        if: contains(steps.*.outcome, 'failure')
        run: exit 1


  post_next_step_content:
    name: Post next step content
    needs: [check_step_work]
    runs-on: ubuntu-latest

    steps:
      - name: Find Exercise Issue
        id: find-exercise-issue
        uses: skills/exercise-toolkit/actions/find-exercise-issue@find-exercise-issue-action

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/exercise-toolkit
          path: exercise-toolkit
          ref: v0.4.0

      - name: Create comment - add step content
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file "$STEP_4_FILE"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ steps.find-exercise-issue.outputs.issue-url }}

      - name: Create comment - watching for progress
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file exercise-toolkit/markdown-templates/step-feedback/watching-for-progress.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ steps.find-exercise-issue.outputs.issue-url }}

      - name: Disable current workflow and enable next one
        run: |
          gh workflow disable "${{github.workflow}}"
          gh workflow enable "Step 4"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
